# Generated by Django 4.2.7 on 2023-12-02 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 0, 25, 41, 842073)),
        ),
    ]
